version: '3'
services:
  kult-resizer:
    env_file:
      variables.env
    image: 'kult-resizer:local-latest'
    build:
      context: '.'
      dockerfile: 'Dockerfile'
    ports:
      - 1811:80
    volumes:
       - ./src:/var/www/html
